var BATTLEFIELD_WIDTH = 1550,
	BATTLEFIELD_HEIGHT = 1050,

	VEHICLE_FACTORY_PRICE = 1200,
	VEHICLE_FACTORY_ENERGY_USE = 400,
	VEHICLE_FACTORY_PROTECTION = 800,
	VEHICLE_FACTORY_WIDTH = 2,
	VEHICLE_FACTORY_HEIGHT = 2,

	VEHICLE_WIDTH = 1,
	VEHICLE_HEIGHT = 1,

	// UNITS
	SCOUT_PROTECTION = 100,
	SCOUT_PRICE = 300,
	SCOUT_SPEED = 2,
	SCOUT_FIREPOWER = 5,
	SCOUT_FIRERANGE = 200,
	SCOUT_FIRESPEED = 10,
	SCOUT_WIDTH = 50,
	SCOUT_HEIGHT = 50,

	TANK_PROTECTION = 100,
	TANK_PRICE = 600,
	TANK_SPEED = 1,
	TANK_FIREPOWER = 25,
	TANK_FIRERANGE = 300,
	TANK_FIRESPEED = 5,
	TANK_WIDTH = 50,
	TANK_HEIGHT = 50,

	GRID_SIZE = 50;